sudo: required
services:
  - docker

before_install:
  - docker build -t markp795/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run markp795/react-test npm test -- --coverage

after_success:
  - docker build -t markp795/multi-client ./client
  - docker build -t markp795/multi-nginx ./nginx
  - docker build -t markp795/multi-server ./server
  - docker build -t markp795/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push markp795/multi-client  
  - docker push markp795/multi-nginx 
  - docker push markp795/multi-server  
  - docker push markp795/multi-worker
    
  
